server:
  port: 9002

spring:
  application:
    name: testify-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

  datasource:
    url: jdbc:postgresql://localhost:5432/testify_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      '[ddl-auto]': update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Cấu hình Virtual Threads (Spring Boot 3.2+)
  threads:
    virtual:
      enabled: true

# Tùy chỉnh config riêng của Testify
testify:
  log-dir: ./logs
  max-concurrent-requests: 100
